### ISSUE TITLE
more explicit metrics API  ?

### ISSUE THREAD

**Issue by remiadon** [simai-ml/MAPIE#19]
Hi there,

scikit-learn metrics names are usually suffixed by `_score` or `_error`
From what I understand the `coverage` is a scoring function (?)

Also, could the name of the function be a bit more specific. I am a newcomer and just had a quick look at the paper,
but `coverage` can mean many things to me.
Could it be renamed something like `target_coverage_score` ??

Finally, an example could be added in the doc.
The shortest example I could get is the following
```python
>>> import numpy as np; from sklearn.linear_model import LinearRegression; from sklearn.datasets import make_regression
>>> regressor = LinearRegression()
>>> X, y = make_regression(n_samples=500, n_features=1, noise=20, random_state=59)
>>> from mapie.estimators import MapieRegressor
>>> mapie = MapieRegressor(regressor).fit(X, y)
>>> X_pi = np.linspace(X.min(), X.max(), 100).reshape(-1, 1)
>>> y_preds = mapie.predict(X_pi)
>>> from mapie.metrics import coverage
>>> coverage(*y_preds.T)
1.0
```

**Comment by vtaquet** [comment]
Hi Rémi,

Thanks for submitting the first issue of MAPIE ! We changed the name of the function to `coverage_score` and add an example in the quickstart of the documentation and of the github README.
