### ISSUE TITLE
[DOCUMENTATION] Fix typos

### ISSUE THREAD

**Issue by alize-papp** [simai-ml/MAPIE#36]
Hi, great work on the library! I'm reading the documentation, it's very interesting. I spotted a few typos in the documentation, would it be okay if I proof-read the documentation, corrected the typos and opened a PR for that?

**Comment by vtaquet** [comment]
Hi, thanks for submitting an issue and for reading the documentation !

Please feel free to proof-read the documentation and open a PR. Just make sure there is no warning when you build the documentation with `make html`. If you only modify the documentation files, there's no need for installing the development environment. 

Thanks !
